server:
  port: 6480

spring:
  application:
    name:
      my_bot

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5434}/${POSTGRES_DB_NAME:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:46379}



vk:
  mode: longpoll
  group:
   id: 194191149
   token: vk1.a.P45bT6TnDD5h5pNP5NYac_6bznB2UBXYlnWpPrySMD19ZnQeRhqbz_FFkrClIapmsOt7Zow9eWAWimaI5O4G0z85PBA2k95iSfgXrYGoPQEWTBiq8_Mzx3KrtEKV1WEj0FqT_2CrlOIY_E-oiSWP_HFwjzetSQWphofKZSQ6W5RCPeczGRtFd_XTjHXiIYexZ_fvme3Fz-Avg7ccTkLjAQ
   confirmation: 06797a66
