spring:
  application:
    name:
      my_bot



vk:
 access-token: vk1.a.2eXAaw-0fKXjILCQrVtywe_Itf-I9N9uJY5rXZAA-PSNOvUXA6KGA8ZqaPj9GaLH1UEjzGXnxFrHdInuIbO7hfNgfLFgsM_v9_2ovTsYj97cadVOYaAugljO3Iy8O6Y08lpdbpjPUNs7qvc5PpBzOvhLCwPPxhSXL8EeocxpLfugvy16KadQA4pEQ6hfD7y5