
CREATE SEQUENCE IF NOT EXISTS my_seq START WITH 1 INCREMENT BY 50;


CREATE TABLE IF NOT EXISTS all_users (
                                         user_id BIGINT PRIMARY KEY,
                                         is_banned BOOLEAN NOT NULL,
                                         bound_chat BIGINT,
                                         full_name_in_nom VARCHAR(255),
    full_name_in_gen VARCHAR(255),
    full_name_in_dat VARCHAR(255),
    full_name_in_acc VARCHAR(255),
    full_name_in_ins VARCHAR(255),
    full_name_in_abl VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS chat_member (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           chat_id BIGINT NOT NULL,
                                           user_id BIGINT NOT NULL,
                                           role_priority INT NOT NULL,
                                           is_chat_admin BOOLEAN,
                                           presence_type VARCHAR(50),
    invited_by_id BIGINT,
    first_appearance TIMESTAMP,
    immune_role_priority INT,
    is_dm_responses_enabled BOOLEAN
    );

CREATE TABLE IF NOT EXISTS command_log_entity (
                                                  id BIGINT DEFAULT nextval('my_seq') PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    from_id BIGINT NOT NULL,
    command_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
    );

CREATE TABLE IF NOT EXISTS timer_entity (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            chat_id BIGINT NOT NULL,
                                            creator_id BIGINT NOT NULL,
                                            type VARCHAR(50) NOT NULL,
    full_command TEXT,
    next_execution TIMESTAMP NOT NULL,
    interval_seconds BIGINT,
    custom_execution_limit INT,
    execution_counter INT NOT NULL DEFAULT 0
    );

CREATE TABLE IF NOT EXISTS role (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    chat_id BIGINT NOT NULL,
                                    role_priority INT NOT NULL,
                                    role_name VARCHAR(255) NOT NULL,
    CONSTRAINT unique_chat_role_name UNIQUE (chat_id, role_name),
    CONSTRAINT unique_chat_role_priority UNIQUE (chat_id, role_priority)
    );

CREATE TABLE IF NOT EXISTS message_log_entity (
                                                  id BIGINT DEFAULT nextval('my_seq') PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    from_id BIGINT NOT NULL,
    conversation_message_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    symbols_quantity INT NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    is_forwarded_to_log_chat BOOLEAN,
    CONSTRAINT unique_chat_conversation UNIQUE (chat_id, conversation_message_id)
    );

CREATE TABLE IF NOT EXISTS bans (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    chat_id BIGINT NOT NULL,
                                    member_id BIGINT NOT NULL,
                                    banned_at TIMESTAMP NOT NULL,
                                    banned_until TIMESTAMP,
                                    reason TEXT,
                                    banned_by BIGINT NOT NULL,
                                    CONSTRAINT unique_chat_member_ban UNIQUE (chat_id, member_id)
    );

CREATE TABLE IF NOT EXISTS chat (
                                    chat_id BIGINT PRIMARY KEY,
                                    chat_title TEXT,
                                    prefix CHAR(1),
    last_sync_time TIMESTAMP,
    silent_restriction BOOLEAN NOT NULL,
    message_replying BOOLEAN NOT NULL,
    time_zone_type VARCHAR(50) NOT NULL,
    ban_time_period_sec BIGINT,
    warn_time_period_sec BIGINT,
    warn_max_quantity INT NOT NULL,
    auto_unban BOOLEAN NOT NULL,
    chat_code VARCHAR(255) NOT NULL UNIQUE,
    bound_log_chat BIGINT,
    bound_submanager_id BIGINT,
    submanager_chat_id BIGINT,
    is_sub_posts_enabled BOOLEAN,
    CONSTRAINT uk_chat_bound_submanager UNIQUE (bound_submanager_id, submanager_chat_id)
    );

CREATE TABLE IF NOT EXISTS warn_entity (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           chat_id BIGINT NOT NULL,
                                           member_id BIGINT NOT NULL,
                                           created_at TIMESTAMP NOT NULL,
                                           expires_at TIMESTAMP,
                                           reason TEXT,
                                           given_by BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS member_permission (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 chat_id BIGINT NOT NULL,
                                                 command_name VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    is_allowed BOOLEAN NOT NULL,
    CONSTRAINT unique_chat_command_user UNIQUE (chat_id, command_name, user_id)
    );

CREATE TABLE IF NOT EXISTS role_permission (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               chat_id BIGINT NOT NULL,
                                               command_name VARCHAR(255) NOT NULL,
    role_priority INT NOT NULL,
    CONSTRAINT unique_chat_command UNIQUE (chat_id, command_name)
    );




CREATE INDEX IF NOT EXISTS idx_bound_chat ON all_users(bound_chat);

CREATE INDEX IF NOT EXISTS idx_chat_member_chat_id ON chat_member(chat_id);
CREATE INDEX IF NOT EXISTS idx_chat_member_user_id ON chat_member(user_id);

CREATE INDEX IF NOT EXISTS idx_command_log_chat_id ON command_log_entity(chat_id);
CREATE INDEX IF NOT EXISTS idx_command_log_created_at ON command_log_entity(created_at);

CREATE INDEX IF NOT EXISTS idx_timer_chat_id ON timer_entity(chat_id);
CREATE INDEX IF NOT EXISTS idx_timer_next_execution ON timer_entity(next_execution);

CREATE INDEX IF NOT EXISTS idx_created_at ON message_log_entity(created_at);
CREATE INDEX IF NOT EXISTS idx_from_id ON message_log_entity(from_id);

CREATE INDEX IF NOT EXISTS idx_banned_until ON bans(banned_until);

CREATE INDEX IF NOT EXISTS idx_bound_log_chat ON chat(bound_log_chat);

CREATE INDEX IF NOT EXISTS idx_warn_chat_id ON warn_entity(chat_id);
CREATE INDEX IF NOT EXISTS idx_warn_member_id ON warn_entity(member_id);
CREATE INDEX IF NOT EXISTS idx_warn_expires_at ON warn_entity(expires_at);